<html>
<body>

<p><center><h1> SEMINAR HALL BOOKING </h1></center><br>
<marquee 
behaviour="slide"
direction="right"> welcome visitor 
</marquee>



<b> kuvempu kalakshthra</b>
<p>
ID     :       1<br>

name:kuvempu kalakshethra<br>
capacity:100<br>
place: 1st floor<br>
</p>
<a href="p1.php?"><button>GO</button></a>
<br>


<b>mba seminar hall</b>
<p> 
ID     :       2<br>
name:mba seminar hall<br>
capacity:100<br>
place: 7th floor<br>
</p>
<a href="p2.php?"><button>GO</button></a>


</body>
</html>